Start linting
Happy0/ssb-chess pull request #76
Opened 2018-08-15 23:50 UTC by christianbundy

Continued the cleanup from before, lots of manual tinkering but everything still looks right. I haven't tested this (other than `npm test`), but this removes a *lot* of dead code. Here are the things I was scared of and didn't touch:

- [`eqeqeq`](https://eslint.org/docs/rules/eqeqeq): Ideally we'd be using `===` instead of `==`, but I'm not familiar enough to know where that's trivial and where it's going to be a giant hairball
- [`import/no-extraneous-dependencies`](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-extraneous-dependencies.md): ESLint *really* wants us to install everything we `require()`, so requiring Electron in `main.js` complains that Electron shouldn't be a devDependency. Maybe it's correct? I'm not familiar enough.
- [`no-param-reassign`](https://eslint.org/docs/rules/no-param-reassign): didn't have time to change these, although I might have a clever fix for it.
- [`no-use-before-define`](https://eslint.org/docs/rules/no-use-before-define): basically just organizing functions so that they only call functions later in the file -- I'm pretty sure a computer could do this pretty well but my human brain is bad at it.

Let me know if you see anything funky!

2018-08-16 11:32 UTC, Happy0 commented
I also seen a:

```
ReferenceError: otherPlayer is not defined
    at Object.keys.forEach (/home/happy0/projects/ssb-chess/ssb_ctrl/game.js:203:29)
```

2018-08-16 11:32 UTC, Happy0 requested changes

2018-08-16 11:32 UTC, Happy0 commented on inject.js
> +  throw new Error('Unexpected location ID: ', location);
I think for `depject` to work, this has to return undefined if it doesn't handle the location (to signal the next handler should be tried.)

This stops patchbay starting as the error is thrown immediately.

2018-08-16 11:32 UTC, Happy0 commented on ui/game/PieceGraveyard.js
> +    Object.keys(materialDiff[colour]).forEach((pieceName) => {
This throws an error upon opening a game now.

```
TypeError: Cannot convert undefined or null to object
```

Maybe we can do something more null safe here?

2018-08-16 11:35 UTC, Happy0 commented
Thanks for getting this underway, btw :)

2018-08-16 14:05 UTC, christianbundy commented
Thanks for taking the time to give me feedback! I pushed some new code that seems reasonable in every way, *except* I had to switch the `++` and `--` logic for the piece graveyard. At first glance I'm not sure I completely understand the logic behind the code, but the original code was resulting in negative integers being passed to `R.repeat()`. Any idea why that might be? The fact that flipping the logic fixed the error is weird.

2018-08-20 11:38 UTC, Happy0 commented
I've checked out your branch and I'll see if I can reproduce the electron moves issue :) (once I have someone to move against :P)

2018-08-20 21:38 UTC, Happy0 commented
@christianbundy I can move fine when I'm on your branch (and using `./node_modules/electron/dist/electron main.js`).

You getting any errors in the developer console?

2018-08-20 21:46 UTC, merged

2018-08-21 00:35 UTC, christianbundy commented
No errors, weird! I'll update if I notice anything else funky, thanks for the merge. :deciduous_tree: